### PR TITLE
Export all interfaces and types

### LINKED ISSUE #18: Please export all types and interfaces.
Hello. I want to use types and interfaces without type inference.

I can't write code like below because d.ts file does not export anything.

```
const rgbToCss = (rgb: RGB): string => {
    const r = Math.round(rgb.r * 255);
    const g = Math.round(rgb.g * 255);
    const b = Math.round(rgb.b * 255);
    return `rgb(${r}, ${g}, ${b})`;
};
```

I created PR that exports all types and interfaces.

Thank you.

### PR DESCRIPTION
**Pull request by hanc1208**
Resolves #18 

Just exported all interfaces and types and excluded from global namespace.

I didn't adjust indent for easy reviewing.

### CODE REVIEW

**Comment by emartinfigma** [comment]
(Just found this PR.)  I like the idea of this, but won't it break existing users who don't have import statements?

**Comment by hanc1208** [comment]
@emartinfigma Typescript always have import statements, doesn't it?

**Comment by emartinfigma** [comment]
No, this file declares globals, which can be used without import statements.  This matches the plugin hosting environment, where the `figma` symbol is available without any import.

**Comment by hanc1208** [comment]
@emartinfigma I got it. I have written this PR to type the Figma API when I don't know that Figma API and Figma Plguin API is significally different. I will close this PR.

**Pull request closed without merging**
